# Generated by Django 5.2.7 on 2025-10-07 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('total_emails', models.IntegerField(default=0)),
                ('completed_emails', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('format_valid', models.BooleanField(default=False)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('mx_records', models.JSONField(blank=True, null=True)),
                ('smtp_status', models.CharField(blank=True, max_length=100, null=True)),
                ('spf_valid', models.CharField(blank=True, max_length=100, null=True)),
                ('dkim_valid', models.CharField(blank=True, max_length=100, null=True)),
                ('dmarc_valid', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BatchEmailResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_results', to='core.batchjob')),
                ('email_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.emailvalidationresult')),
            ],
        ),
    ]
