# Generated by Django 5.2.7 on 2025-10-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
