# Generated by Django 5.2.7 on 2025-10-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_batchjob_started_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailvalidationresult',
            name='dkim_valid',
        ),
        migrations.RemoveField(
            model_name='emailvalidationresult',
            name='dmarc_valid',
        ),
        migrations.RemoveField(
            model_name='emailvalidationresult',
            name='spf_valid',
        ),
        migrations.AddField(
            model_name='emailvalidationresult',
            name='dkim_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailvalidationresult',
            name='dmarc_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailvalidationresult',
            name='spf_valid',
            field=models.BooleanField(default=False),
        ),
    ]
